# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bf016beed5b792fada66729a1b99a08fdd09bdb0db0333cb68e02eeddc25350c8e92d4b931ac7622b8b7697905babd74bc834b6abb46be7b2b65c1c7bdd535

test:
  secret_key_base: 90272482b7c1c13324b0d36b903f68176869057c57f022658fbf6019d1859e4486f3fd7b69859bd5dd2446f182194e19baa902819b5b7900ea99d703e4b51d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
